#!/bin/sh

#
# This batch file does a primitive performance test of the network
#

JDK_CLASSES="/usr/java_dev2/jre/lib/rt.jar"
JAVA_COMMAND="java"

$JAVA_COMMAND $1 $2 $3 $4 $5  -classpath .:middleware.jar:$JDK_CLASSES COM.ibm.opicmpdh.middleware.MiddlewareWatchdog

#
# end of script
#
