-- SCRIPT FOR INITIALIZING CERTAIN ECCCM TABLES - USE WITH DB2BATCH
--
-- $Log: eccm.refload.sql,v $
-- Revision 1.9  2004/01/28 21:52:07  dave
-- checking back in some minor changes
--
-- Revision 1.8  2004/01/26 19:03:50  dave
-- more ECCM minor updates to script files
--
-- Revision 1.7  2004/01/23 19:56:12  dave
-- changed KZ to NLSID = 7 in our reference tables
--
-- Revision 1.6  2004/01/19 03:29:53  dave
-- more syntax
--
-- Revision 1.5  2004/01/16 18:58:10  dave
-- added all the table creates to refload
--
-- Revision 1.4  2004/01/16 18:31:42  dave
-- adding in other tables
--
-- Revision 1.3  2004/01/07 00:21:03  dave
-- more scripting
--
-- Revision 1.2  2003/12/30 19:43:24  dave
-- changes
--
-- Revision 1.1  2003/12/16 22:44:19  dave
-- new script for reference tables CR1121034237
--
--
--

-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.ELEMENT_REPORT
------------------------------------------------
-- DROP TABLE ECCM.ELEMENT_REPORT;
 CREATE TABLE ECCM.ELEMENT_REPORT  (
    PARTNUMBER VARCHAR(36) NOT NULL ,
    COUNTRYNAME VARCHAR(45) NOT NULL ,
    AUDIENCE VARCHAR(254) NOT NULL ,
    LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    REGION VARCHAR(50) ,
    PARTDESCRIPTION VARCHAR(252) ,
    WWPARTNUMBER VARCHAR(36) ,
    FAMILYNAME VARCHAR(60) ,
    SERIESNAME VARCHAR(254) ,
    SOURCESYSTEM VARCHAR(10) ,
    TARGETANNOUNCE VARCHAR(30) ,
    WITHDRAWALDATE VARCHAR(30) ,
    SALESSTATUS CHAR(2) ,
    STATUS VARCHAR(75) ,
    RULENAME VARCHAR(254) ,
    ELEMENTNAME VARCHAR(36) ,
    ELEMENTVALUE VARCHAR(1024) ,
    USERNAME VARCHAR(128) ,
    LASTMODIFIED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)
   ;
ALTER TABLE ECCM.ELEMENT_REPORT PCTFREE 10;
CREATE UNIQUE INDEX ECCM.ELEMENT_REPORT_PK ON ECCM.ELEMENT_REPORT(PARTNUMBER, COUNTRYNAME, AUDIENCE, LASTUPDATED);
CREATE INDEX ECCM.XIE1ELEMENT_REPORT ON ECCM.ELEMENT_REPORT (COUNTRYNAME ASC, AUDIENCE ASC) PCTFREE 10 CLUSTER ;

------------------------------------------------
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.IFMLOCK
------------------------------------------------
-- DROP TABLE ECCM.IFMLOCK;
CREATE TABLE ECCM.IFMLOCK  (
    PROCESS_ID INTEGER NOT NULL ,
    PROCESS_NAME VARCHAR(30) NOT NULL ,
    STATUS INTEGER NOT NULL ,
    START_TIME TIMESTAMP ,
    END_TIME TIMESTAMP )
   ;
ALTER TABLE ECCM.IFMLOCK PCTFREE 10;
CREATE UNIQUE INDEX ECCM.IFMLOCK_PK ON ECCM.IFMLOCK (PROCESS_ID);
CREATE INDEX ECCM.XIE1IFMLOCK ON ECCM.IFMLOCK (END_TIME ASC, START_TIME ASC) PCTFREE 10 CLUSTER ;

------------------------------------------------
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.RATECARDDESC
------------------------------------------------
-- DROP TABLE ECCM.RATECARDDESC;
 CREATE TABLE ECCM.RATECARDDESC  (
    COUNTRYCODE CHAR(2) NOT NULL ,
    SHIPPINGCONDITION CHAR(2) NOT NULL ,
    NLSID INTEGER NOT NULL ,
    DESCRIPTION VARCHAR(40) ,
    LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)
   ;
ALTER TABLE ECCM.RATECARDDESC PCTFREE 10;
CREATE UNIQUE INDEX ECCM.RATECARDDESC_PK ON ECCM.RATECARDDESC (COUNTRYCODE ASC, SHIPPINGCONDITION ASC, NLSID ASC) PCTFREE 10 CLUSTER ;

------------------------------------------------
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.RATE_CARD
------------------------------------------------
-- DROP TABLE ECCM.RATE_CARD;
 CREATE TABLE ECCM.RATE_CARD  (
    RATECARDCODE CHAR(10) NOT NULL ,
    COUNTRYCODE CHAR(3) NOT NULL ,
    SHIPPINGCONDITION CHAR(2) NOT NULL ,
    PRICEVALIDFROMDATE DATE NOT NULL ,
    PRICEAMOUNT DECIMAL(16,3) ,
    CURRENCYCODE CHAR(5) ,
    PRICEVALIDTODATE DATE ,
    SOURCESYSTEM VARCHAR(10) ,
    LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    MARKEDFORDELETION CHAR(1) )
    ;
ALTER TABLE ECCM.RATE_CARD PCTFREE 10;
CREATE UNIQUE INDEX ECCM.RATE_CARD_PK ON ECCM.RATECARD(RATECARDCODE, COUNTRYCODE, SHIPPINGCONDITION, PRICEVALIDFROMDATE);
CREATE INDEX ECCM.WZ1RATE_CARD1 ON ECCM.RATE_CARD (LASTUPDATED ASC, MARKEDFORDELETION ASC, SOURCESYSTEM ASC, CURRENCYCODE ASC, PRICEAMOUNT ASC,  PRICEVALIDFROMDATE ASC, PRICEVALIDTODATE ASC, SHIPPINGCONDITION ASC,  COUNTRYCODE ASC, RATECARDCODE ASC);
CREATE INDEX ECCM.XIE1RATE_CARD ON ECCM.RATE_CARD (COUNTRYCODE ASC, RATECARDCODE ASC) PCTFREE 10 CLUSTER ;

------------------------------------------------
-- MADE DROP IMMUNE FROM ODSINIT
-----------------------------------------------
-- DDL Statements for table ECCM.SECURITY
------------------------------------------------
-- DROP TABLE ECCM.SECURITY;
 CREATE TABLE ECCM.SECURITY  (
    USERID VARCHAR(100) NOT NULL ,
    LISTTYPE CHAR(1) NOT NULL ,
    LISTVALUE VARCHAR(254) NOT NULL ,
    NAME VARCHAR(254) ,
    LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    LASTMODIFIED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)
    ;
ALTER TABLE ECCM.SECURITY PCTFREE 10;
CREATE UNIQUE INDEX ECCM.SECURITY_PK ON ECCM.SECURITY (USERID, LISTTYPE, LISTVALUE);


------------------------------------------------
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.PRODUCT_PRICE
------------------------------------------------
-- DROP TABLE ECCM.PRODUCT_PRICE;
 CREATE TABLE ECCM.PRODUCT_PRICE  (
    PARTNUMBER CHAR(18) NOT NULL ,
    CTOVARIANTPARTNUMBER CHAR(18) NOT NULL ,
    COUNTRYCODE CHAR(3) NOT NULL ,
    DISTRIBUTIONCHANNEL CHAR(2) NOT NULL ,
    PRICEVALIDTODATE DATE NOT NULL ,
    PRICETYPE CHAR(4) NOT NULL ,
    MATERIALSTATUS CHAR(2) ,
    MATERIALSTATUSDATE DATE ,
    PRICEAMOUNT DECIMAL(16,3) ,
    CURRENCYCODE CHAR(5) ,
    PRICEVALIDFROMDATE DATE ,
    CALLFORQUOTE CHAR(1) ,
    PRECEDENCE SMALLINT ,
    SOURCESYSTEM VARCHAR(10) ,
    LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    MARKEDFORDELETION CHAR(1) )
  ;
 ALTER TABLE ECCM.PRODUCT_PRICE PCTFREE 10;

CREATE UNIQUE INDEX ECCM.PRODUCT_PRICE_PK ON ECCM.PRODUCT_PRICE(PARTNUMBER, CTOVARIANTPARTNUMBER, COUNTRYCODE, DISTRIBUTIONCHANNEL, PRICEVALIDTODATE,  PRICETYPE);
CREATE INDEX ECCM.WZ1PRODUCT_PRICE1 ON ECCM.PRODUCT_PRICE (LASTUPDATED ASC, PARTNUMBER ASC, CTOVARIANTPARTNUMBER ASC, COUNTRYCODE ASC, DISTRIBUTIONCHANNEL ASC, PRICEVALIDTODATE ASC, PRICETYPE ASC);
CREATE INDEX ECCM.XIE1PRODUCT_PRICE ON ECCM.PRODUCT_PRICE (COUNTRYCODE ASC, PRICEVALIDTODATE ASC) PCTFREE 10 CLUSTER ;

-------------------------------------------------
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.PROD_PRODUCT_PRICE
------------------------------------------------
-- DROP TABLE ECCM.PROD_PRODUCT_PRICE;
 CREATE TABLE ECCM.PROD_PRODUCT_PRICE  (
    PARTNUMBER CHAR(18) NOT NULL ,
    CTOVARIANTPARTNUMBER CHAR(18) NOT NULL ,
    COUNTRYCODE CHAR(3) NOT NULL ,
    DISTRIBUTIONCHANNEL CHAR(2) NOT NULL ,
    PRICEVALIDTODATE DATE NOT NULL ,
    PRICETYPE CHAR(4) NOT NULL ,
    MATERIALSTATUS CHAR(2) ,
    MATERIALSTATUSDATE DATE ,
    PRICEAMOUNT DECIMAL(16,3) ,
    CURRENCYCODE CHAR(5) ,
    PRICEVALIDFROMDATE DATE ,
    CALLFORQUOTE CHAR(1) ,
    PRECEDENCE SMALLINT ,
    SOURCESYSTEM VARCHAR(10) ,
    LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    MARKEDFORDELETION CHAR(1) )
  ;
ALTER TABLE ECCM.PROD_PRODUCT_PRICE PCTFREE 10;

DROP UNIQUE INDEX ECCM.PROD_PRODUCT_P_PK;
CREATE UNIQUE INDEX ECCM.PROD_PRODUCT_P_PK ON ECCM.PROD_PRODUCT_PRICE (PARTNUMBER,CTOVARIANTPARTNUMBER, COUNTRYCODE, DISTRIBUTIONCHANNEL, PRICEVALIDTODATE, PRICETYPE);
CREATE INDEX ECCM.WZ1PROD_PRODUCT_P ON ECCM.PROD_PRODUCT_PRICE(LASTUPDATED ASC, PARTNUMBER ASC, CTOVARIANTPARTNUMBER ASC, COUNTRYCODE ASC, DISTRIBUTIONCHANNEL ASC, PRICEVALIDTODATE ASC, PRICETYPE ASC);
CREATE INDEX ECCM.XIE1PROD_PRODUCT_P ON ECCM.PROD_PRODUCT_PRICE(COUNTRYCODE ASC, PRICEVALIDTODATE ASC) PCTFREE 10 CLUSTER ;
CREATE INDEX ECCM.XIE2PROD_PRODUCT_P ON ECCM.PROD_PRODUCT_PRICE(CURRENCYCODE ASC)PCTFREE 10 ;


------------------------------------------------
-- Added INT SCRIPT per Mary
------------------------------------------------
-- DDL Statements for table INT.TIMECODE
------------------------------------------------
--DROP TABLE INT.TIMECODE;
CREATE TABLE INT.TIMECODE  (
    ENTITYID INTEGER NOT NULL ,
    NLSID INTEGER NOT NULL ,
    TIMECODE INTEGER ,
    ENTITYTYPE VARCHAR(36) NOT NULL )
   IN USERSPACE1 ;
 ALTER TABLE INT.TIMECODE PCTFREE 10;

CREATE UNIQUE INDEX INT.TIMECODE_PK ON INT.TIMECODE (ENTITYID, ENTITYTYPE,NLSID);


------------------------------------------------
-- CALLED OUT IN TABLE SPEC
-- CONVERTED DWB
-- COMPILED DWB
-- CHECKED FOR FINAL SCRIPT
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.PROD_CHAR_VALUE
------------------------------------------------
-- DROP TABLE ECCM.PROD_CHAR_VALUE;
 CREATE TABLE ECCM.PROD_CHAR_VALUE  (
      PARTNUMBER CHAR(18) NOT NULL ,
      CHARACTERISTICNAME CHAR(30) NOT NULL ,
      CHARACTERISTICVALUE CHAR(30) NOT NULL ,
      LOWERLIMIT DOUBLE ,
      UPPERLIMIT DOUBLE ,
      SOURCESYSTEM VARCHAR(10) ,
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)
 ;
ALTER TABLE ECCM.PROD_CHAR_VALUE PCTFREE 10;
CREATE UNIQUE INDEX  ECCM.PROD_CHAR_VALUE_PK ON PROD_CHAR_VALUE(PARTNUMBER, CHARACTERISTICNAME,CHARACTERISTICVALUE);


------------------------------------------------
-- GOT FROM MTM
-- MADE DROP IMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.CHAR_VALUE
------------------------------------------------
--DROP TABLE ECCM.CHAR_VALUE;
CREATE TABLE ECCM.CHAR_VALUE  (
    PARTNUMBER CHAR(18) NOT NULL ,
    CHARACTERISTICNAME CHAR(30) NOT NULL ,
    CHARACTERISTICVALUE CHAR(30) NOT NULL ,
    LOWERLIMIT DOUBLE ,
    UPPERLIMIT DOUBLE ,
    SOURCESYSTEM VARCHAR(10) ,
    LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    MARKEDFORDELETION CHAR(1) )
   ;
ALTER TABLE ECCM.CHAR_VALUE PCTFREE 10;
CREATE UNIQUE INDEX ECCM.CHAR_VALUE_PK ON ECCM.CHAR_VALUE(PARTNUMBER, CHARACTERISTICNAME, CHARACTERISTICVALUE);

-----------------------------------------------
-- CONVERTED DWB
-- COMPILED DWB
-- CHECKED FOR FINAL SCRIPT
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.PROD_RATE_CARD
------------------------------------------------
--DROP TABLE ECCM.PROD_RATE_CARD;
CREATE TABLE ECCM.PROD_RATE_CARD  (
    RATECARDCODE CHAR(10) NOT NULL ,
    COUNTRYCODE CHAR(3) NOT NULL ,
    SHIPPINGCONDITION CHAR(2) NOT NULL ,
    PRICEVALIDFROMDATE DATE NOT NULL ,
    PRICEAMOUNT DECIMAL(16,3) ,
    CURRENCYCODE CHAR(5) ,
    PRICEVALIDTODATE DATE ,
    SOURCESYSTEM VARCHAR(10) ,
    LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)
IN TSPACE01 INDEX IN ISPACE01;
ALTER TABLE ECCM.PROD_RATE_CARD PCTFREE 10;
CREATE UNIQUE INDEX ECCM.PROD_RATE_CARD_PK ON ECCM.PROD_RATE_CARD(RATECARDCODE, COUNTRYCODE, SHIPPINGCONDITION,PRICEVALIDFROMDATE);
CREATE INDEX ECCM.WZ1PROD_RATE_CARD1 ON ECCM.PROD_RATE_CARD (RATECARDCODE ASC,COUNTRYCODE ASC,SHIPPINGCONDITION ASC,PRICEVALIDTODATE ASC,LASTUPDATED ASC,SOURCESYSTEM ASC,CURRENCYCODE ASC, PRICEAMOUNT ASC, PRICEVALIDFROMDATE ASC);
CREATE INDEX ECCM.XIE1PROD_RATE_CARD ON ECCM.PROD_RATE_CARD (COUNTRYCODE ASC) PCTFREE 10 CLUSTER ;

------------------------------------------------------------------------------------------
--  SET UP DATA FOR ECCM ODS - Gbli Mapping table 
------------------------------------------------------------------------------------------
drop table gbli.gamap;
create table gbli.gamap (
  NAME CHAR(32) NOT NULL,
  CODE CHAR(6) NOT NULL,
  NLSID INT NOT NULL,
  GENAREANAME_FC CHAR(16) NOT NULL
);
drop index gbli.gamap_ix1;
create index gbli.gamap_ix1 on gbli.gamap(GENAREANAME_FC, NLSID);

--
-- INSERT STATEMENTS
--
INSERT INTO GBLI.GAMAP VALUES('Andorra', 'AD', 1, '10874');
INSERT INTO GBLI.GAMAP VALUES('Utd.Arab.Emir.', 'AE', 1, '11019');
INSERT INTO GBLI.GAMAP VALUES('Afghanistan', 'AF', 1, '10871');
INSERT INTO GBLI.GAMAP VALUES('Albania', 'AL', 1, '10872');
INSERT INTO GBLI.GAMAP VALUES('Armenia', 'AM', 1, '10877');
INSERT INTO GBLI.GAMAP VALUES('Angola', 'AO', 1, '10875');
INSERT INTO GBLI.GAMAP VALUES('Argentina', 'AR', 1, '10876');
INSERT INTO GBLI.GAMAP VALUES('ASEAN-Cty', 'AS', 1, '11048');
INSERT INTO GBLI.GAMAP VALUES('Austria', 'AT', 2, '10879');
INSERT INTO GBLI.GAMAP VALUES('Australia', 'AU', 7, '10878');
INSERT INTO GBLI.GAMAP VALUES('Azerbaijan', 'AZ', 1, '10880');
INSERT INTO GBLI.GAMAP VALUES('Bosnia-Herz.', 'BA', 1, '10887');
INSERT INTO GBLI.GAMAP VALUES('Bangladesh', 'BD', 1, '10881');
INSERT INTO GBLI.GAMAP VALUES('Belgium', 'BE', 7, '10882');
INSERT INTO GBLI.GAMAP VALUES('Burkina-Faso', 'BF', 1, '10892');
INSERT INTO GBLI.GAMAP VALUES('Bulgaria', 'BG', 1, '10891');
INSERT INTO GBLI.GAMAP VALUES('Bharain', 'BH', 1, '10884');
INSERT INTO GBLI.GAMAP VALUES('Burundi', 'BI', 1, '10893');
INSERT INTO GBLI.GAMAP VALUES('Benin', 'BJ', 1, '10883');
INSERT INTO GBLI.GAMAP VALUES('Brunei Dar-es-S', 'BN', 1, '10890');
INSERT INTO GBLI.GAMAP VALUES('Bolivia', 'BO', 1, '10886');
INSERT INTO GBLI.GAMAP VALUES('Brazil', 'BR', 1, '10889');
INSERT INTO GBLI.GAMAP VALUES('Bhutan', 'BT', 1, '10885');
INSERT INTO GBLI.GAMAP VALUES('Botswana', 'BW', 1, '10888');
INSERT INTO GBLI.GAMAP VALUES('White Russia', 'BY', 1, '11025');
INSERT INTO GBLI.GAMAP VALUES('Canada', 'CA', 7, '10896');
INSERT INTO GBLI.GAMAP VALUES('Canada', 'CA', 10, '10896');
INSERT INTO GBLI.GAMAP VALUES('Central Afr.Rep', 'CF', 1, '10898');
INSERT INTO GBLI.GAMAP VALUES('Congo', 'CG', 1, '10904');
INSERT INTO GBLI.GAMAP VALUES('Switzerland', 'CH', 7, '11005');
INSERT INTO GBLI.GAMAP VALUES('Ivory Coast', 'CI', 1, '10939');
INSERT INTO GBLI.GAMAP VALUES('Chile', 'CL', 1, '10900');
INSERT INTO GBLI.GAMAP VALUES('Cameroon', 'CM', 1, '10895');
INSERT INTO GBLI.GAMAP VALUES('China', 'CN', 1, '10901');
INSERT INTO GBLI.GAMAP VALUES('Columbia', 'CO', 1, '10902');
INSERT INTO GBLI.GAMAP VALUES('Costa Rica', 'CR', 1, '10905');
INSERT INTO GBLI.GAMAP VALUES('Cape Verde', 'CV', 1, '10897');
INSERT INTO GBLI.GAMAP VALUES('Cyprus', 'CY', 1, '10907');
INSERT INTO GBLI.GAMAP VALUES('Czech Republic', 'CZ', 7, '10908');
INSERT INTO GBLI.GAMAP VALUES('Germany', 'DE', 2, '10924');
INSERT INTO GBLI.GAMAP VALUES('Djibouti', 'DJ', 1, '10910');
INSERT INTO GBLI.GAMAP VALUES('Denmark', 'DK', 7, '10909');
INSERT INTO GBLI.GAMAP VALUES('Algeria', 'DZ', 1, '10873');
INSERT INTO GBLI.GAMAP VALUES('Ecuador', 'EC', 1, '10911');
INSERT INTO GBLI.GAMAP VALUES('Estonia', 'EE', 1, '10915');
INSERT INTO GBLI.GAMAP VALUES('Egypt', 'EG', 1, '10912');
INSERT INTO GBLI.GAMAP VALUES('EMEA-Cty', 'EM', 1, '11047');
INSERT INTO GBLI.GAMAP VALUES('Eritrea', 'ER', 1, '10914');
INSERT INTO GBLI.GAMAP VALUES('Spain', 'ES', 6, '11000');
INSERT INTO GBLI.GAMAP VALUES('Ethiopia', 'ET', 1, '10916');
INSERT INTO GBLI.GAMAP VALUES('Finland', 'FI', 7, '10917');
INSERT INTO GBLI.GAMAP VALUES('France', 'FR', 5, '10918');
INSERT INTO GBLI.GAMAP VALUES('Gabon', 'GA', 1, '10921');
INSERT INTO GBLI.GAMAP VALUES('United Kingdom', 'GB', 7, '11017');
INSERT INTO GBLI.GAMAP VALUES('Georgia', 'GE', 1, '10923');
INSERT INTO GBLI.GAMAP VALUES('French Guinea', 'GF', 1, '10920');
INSERT INTO GBLI.GAMAP VALUES('Ghana', 'GH', 1, '10925');
INSERT INTO GBLI.GAMAP VALUES('Gambia', 'GM', 1, '10922');
INSERT INTO GBLI.GAMAP VALUES('Guinea', 'GN', 1, '10928');
INSERT INTO GBLI.GAMAP VALUES('Guadeloupe', 'GP', 1, '10927');
INSERT INTO GBLI.GAMAP VALUES('Equatorial Guin', 'GQ', 1, '10913');
INSERT INTO GBLI.GAMAP VALUES('Greece', 'GR', 7, '10926');
INSERT INTO GBLI.GAMAP VALUES('Guinea-Bissau', 'GW', 1, '10929');
INSERT INTO GBLI.GAMAP VALUES('Hong Kong', 'HK', 7, '10930');
INSERT INTO GBLI.GAMAP VALUES('Croatia', 'HR', 7, '10906');
INSERT INTO GBLI.GAMAP VALUES('Hungary', 'HU', 7, '10931');
INSERT INTO GBLI.GAMAP VALUES('Indonesia', 'ID', 1, '10934');
INSERT INTO GBLI.GAMAP VALUES('Ireland', 'IE', 7, '10936');
INSERT INTO GBLI.GAMAP VALUES('Israel', 'IL', 1, '10937');
INSERT INTO GBLI.GAMAP VALUES('India', 'IN', 7, '10933');
INSERT INTO GBLI.GAMAP VALUES('Iran', 'IR', 1, '10935');
INSERT INTO GBLI.GAMAP VALUES('Iceland', 'IS', 1, '10932');
INSERT INTO GBLI.GAMAP VALUES('Italy', 'IT', 3, '10938');
INSERT INTO GBLI.GAMAP VALUES('Jordan', 'JO', 1, '10941');
INSERT INTO GBLI.GAMAP VALUES('Japan', 'JP', 4, '10940');
INSERT INTO GBLI.GAMAP VALUES('Kenya', 'KE', 1, '10943');
INSERT INTO GBLI.GAMAP VALUES('Kirghistan', 'KG', 1, '10944');
INSERT INTO GBLI.GAMAP VALUES('Cambodia', 'KH', 1, '10894');
INSERT INTO GBLI.GAMAP VALUES('Comoro', 'KM', 1, '10903');
INSERT INTO GBLI.GAMAP VALUES('South Korea', 'KR', 8, '10999');
INSERT INTO GBLI.GAMAP VALUES('Kuwait', 'KW', 1, '10945');
INSERT INTO GBLI.GAMAP VALUES('Kazakhstan', 'KZ', 7, '10942');
INSERT INTO GBLI.GAMAP VALUES('Laos', 'LA', 1, '10946');
INSERT INTO GBLI.GAMAP VALUES('Lebanon', 'LB', 1, '10948');
INSERT INTO GBLI.GAMAP VALUES('LAD-Cty', 'LD', 1, '11049');
INSERT INTO GBLI.GAMAP VALUES('Liechtenstein', 'LI', 1, '10951');
INSERT INTO GBLI.GAMAP VALUES('Sri Lanka', 'LK', 1, '11001');
INSERT INTO GBLI.GAMAP VALUES('Liberia', 'LR', 1, '10950');
INSERT INTO GBLI.GAMAP VALUES('Lesotho', 'LS', 1, '10949');
INSERT INTO GBLI.GAMAP VALUES('Lithuania', 'LT', 1, '10952');
INSERT INTO GBLI.GAMAP VALUES('Luxembourg', 'LU', 1, '11033');
INSERT INTO GBLI.GAMAP VALUES('Latvia', 'LV', 1, '10947');
INSERT INTO GBLI.GAMAP VALUES('Morocco', 'MA', 1, '10966');
INSERT INTO GBLI.GAMAP VALUES('Monaco', 'MC', 1, '10965');
INSERT INTO GBLI.GAMAP VALUES('Moldavia', 'MD', 1, '10964');
INSERT INTO GBLI.GAMAP VALUES('Madagascar', 'MG', 1, '10954');
INSERT INTO GBLI.GAMAP VALUES('Macedonia', 'MK', 1, '10953');
INSERT INTO GBLI.GAMAP VALUES('Mali', 'ML', 1, '10958');
INSERT INTO GBLI.GAMAP VALUES('Myanmar', 'MM', 1, '10968');
INSERT INTO GBLI.GAMAP VALUES('Martinique', 'MQ', 1, '10959');
INSERT INTO GBLI.GAMAP VALUES('Mauretania', 'MR', 1, '10960');
INSERT INTO GBLI.GAMAP VALUES('Malta', 'MT', 1, '11031');
INSERT INTO GBLI.GAMAP VALUES('Mauritius', 'MU', 1, '10961');
INSERT INTO GBLI.GAMAP VALUES('Maldives', 'MV', 1, '10957');
INSERT INTO GBLI.GAMAP VALUES('Malawi', 'MW', 1, '10955');
INSERT INTO GBLI.GAMAP VALUES('Mexico', 'MX', 1, '10963');
INSERT INTO GBLI.GAMAP VALUES('Malaysia', 'MY', 1, '10956');
INSERT INTO GBLI.GAMAP VALUES('Mozambique', 'MZ', 1, '10967');
INSERT INTO GBLI.GAMAP VALUES('Namibia', 'NA', 1, '10969');
INSERT INTO GBLI.GAMAP VALUES('New Caledonia', 'NC', 1, '10972');
INSERT INTO GBLI.GAMAP VALUES('Niger', 'NE', 1, '10974');
INSERT INTO GBLI.GAMAP VALUES('Nigeria', 'NG', 1, '10975');
INSERT INTO GBLI.GAMAP VALUES('Netherlands', 'NL', 7, '10971');
INSERT INTO GBLI.GAMAP VALUES('Norway', 'NO', 7, '10976');
INSERT INTO GBLI.GAMAP VALUES('Nepal', 'NP', 1, '10970');
INSERT INTO GBLI.GAMAP VALUES('New Zealand', 'NZ', 7, '10973');
INSERT INTO GBLI.GAMAP VALUES('Oman', 'OM', 1, '10977');
INSERT INTO GBLI.GAMAP VALUES('Peru', 'PE', 1, '10980');
INSERT INTO GBLI.GAMAP VALUES('Frenc.Polynesia', 'PF', 1, '10919');
INSERT INTO GBLI.GAMAP VALUES('Philippines', 'PH', 1, '10981');
INSERT INTO GBLI.GAMAP VALUES('Pakistan', 'PK', 1, '10978');
INSERT INTO GBLI.GAMAP VALUES('Poland', 'PL', 7, '10982');
INSERT INTO GBLI.GAMAP VALUES('Portugal', 'PT', 7, '10983');
INSERT INTO GBLI.GAMAP VALUES('Paraguay', 'PY', 1, '10979');
INSERT INTO GBLI.GAMAP VALUES('Qatar', 'QA', 1, '10984');
INSERT INTO GBLI.GAMAP VALUES('Reunion', 'RE', 1, '10985');
INSERT INTO GBLI.GAMAP VALUES('Romania', 'RO', 7, '10986');
INSERT INTO GBLI.GAMAP VALUES('Russian Fed.', 'RU', 1, '10987');
INSERT INTO GBLI.GAMAP VALUES('Rwanda', 'RW', 1, '10988');
INSERT INTO GBLI.GAMAP VALUES('Saudi Arabia', 'SA', 1, '10990');
INSERT INTO GBLI.GAMAP VALUES('Seychelles', 'SC', 1, '10992');
INSERT INTO GBLI.GAMAP VALUES('Sudan', 'SD', 1, '11002');
INSERT INTO GBLI.GAMAP VALUES('Sweden', 'SE', 7, '11004');
INSERT INTO GBLI.GAMAP VALUES('Singapore', 'SG', 7, '10994');
INSERT INTO GBLI.GAMAP VALUES('Slovenia', 'SI', 1, '10996');
INSERT INTO GBLI.GAMAP VALUES('Slovakia', 'SK', 1, '10995');
INSERT INTO GBLI.GAMAP VALUES('Sierra Leone', 'SL', 1, '10993');
INSERT INTO GBLI.GAMAP VALUES('Senegal', 'SN', 1, '10991');
INSERT INTO GBLI.GAMAP VALUES('Somalia', 'SO', 1, '10997');
INSERT INTO GBLI.GAMAP VALUES('Serbia', 'SR', 1, '11032');
INSERT INTO GBLI.GAMAP VALUES('S.Tome,Principe', 'ST', 1, '10989');
INSERT INTO GBLI.GAMAP VALUES('Syria', 'SY', 1, '11006');
INSERT INTO GBLI.GAMAP VALUES('Swaziland', 'SZ', 1, '11003');
INSERT INTO GBLI.GAMAP VALUES('Chad', 'TD', 1, '10899');
INSERT INTO GBLI.GAMAP VALUES('Thailand', 'TH', 1, '11010');
INSERT INTO GBLI.GAMAP VALUES('Tadzhikistan', 'TJ', 1, '11007');
INSERT INTO GBLI.GAMAP VALUES('Turkmenistan', 'TM', 1, '11013');
INSERT INTO GBLI.GAMAP VALUES('Tunisia', 'TN', 1, '11011');
INSERT INTO GBLI.GAMAP VALUES('Turkey', 'TR', 1, '11012');
INSERT INTO GBLI.GAMAP VALUES('Taiwan', 'TW', 1, '11008');
INSERT INTO GBLI.GAMAP VALUES('Tanzania', 'TZ', 1, '11009');
INSERT INTO GBLI.GAMAP VALUES('Ukraine', 'UA', 1, '11016');
INSERT INTO GBLI.GAMAP VALUES('Uganda', 'UG', 1, '11015');
INSERT INTO GBLI.GAMAP VALUES('USA', 'US', 1, '11014');
INSERT INTO GBLI.GAMAP VALUES('Uruguay', 'UY', 1, '11018');
INSERT INTO GBLI.GAMAP VALUES('Uzbekistan', 'UZ', 1, '11020');
INSERT INTO GBLI.GAMAP VALUES('Venezuela', 'VE', 1, '11022');
INSERT INTO GBLI.GAMAP VALUES('Vietnam', 'VN', 1, '11023');
INSERT INTO GBLI.GAMAP VALUES('Vanuatu', 'VU', 1, '11021');
INSERT INTO GBLI.GAMAP VALUES('Wallis,Futuna', 'WF', 1, '11024');
INSERT INTO GBLI.GAMAP VALUES('Yemen', 'YE', 1, '11026');
INSERT INTO GBLI.GAMAP VALUES('Mayotte', 'YT', 1, '10962');
INSERT INTO GBLI.GAMAP VALUES('Yugoslavia', 'YU', 1, '11027');
INSERT INTO GBLI.GAMAP VALUES('South Africa', 'ZA', 7, '10998');
INSERT INTO GBLI.GAMAP VALUES('Zambia', 'ZM', 1, '11029');
INSERT INTO GBLI.GAMAP VALUES('Zaire', 'ZR', 1, '11028');
INSERT INTO GBLI.GAMAP VALUES('Zimbabwe', 'ZW', 1, '11030');


------------------------------------------------
-- Used to support table spec views
-- Converted DWB
-- COMPILED DWB
-- CHECKED FOR FINAL SCRIPT
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.CCECTRY
------------------------------------------------
DROP TABLE ECCM.CCECTRY;
CREATE TABLE ECCM.CCECTRY (
  COUNTRYCODE CHAR (6) NOT NULL
);

CREATE UNIQUE INDEX ECCM.CCECTRY_PK ON ECCM.CCECTRY(COUNTRYCODE);

--
-- Here is are the insert statements
--
INSERT INTO ECCM.CCECTRY VALUES('AT    ');
INSERT INTO ECCM.CCECTRY VALUES('AU    ');
INSERT INTO ECCM.CCECTRY VALUES('BE    ');
INSERT INTO ECCM.CCECTRY VALUES('CA    ');
INSERT INTO ECCM.CCECTRY VALUES('CH    ');
INSERT INTO ECCM.CCECTRY VALUES('CZ    ');
INSERT INTO ECCM.CCECTRY VALUES('DE    ');
INSERT INTO ECCM.CCECTRY VALUES('DK    ');
INSERT INTO ECCM.CCECTRY VALUES('ES    ');
INSERT INTO ECCM.CCECTRY VALUES('FI    ');
INSERT INTO ECCM.CCECTRY VALUES('FR    ');
INSERT INTO ECCM.CCECTRY VALUES('GB    ');
INSERT INTO ECCM.CCECTRY VALUES('GR    ');
INSERT INTO ECCM.CCECTRY VALUES('HK    ');
INSERT INTO ECCM.CCECTRY VALUES('HR    ');
INSERT INTO ECCM.CCECTRY VALUES('HU    ');
INSERT INTO ECCM.CCECTRY VALUES('IE    ');
INSERT INTO ECCM.CCECTRY VALUES('IN    ');
INSERT INTO ECCM.CCECTRY VALUES('IT    ');
INSERT INTO ECCM.CCECTRY VALUES('JP    ');
INSERT INTO ECCM.CCECTRY VALUES('KR    ');
INSERT INTO ECCM.CCECTRY VALUES('NL    ');
INSERT INTO ECCM.CCECTRY VALUES('NO    ');
INSERT INTO ECCM.CCECTRY VALUES('NZ    ');
INSERT INTO ECCM.CCECTRY VALUES('PL    ');
INSERT INTO ECCM.CCECTRY VALUES('PT    ');
INSERT INTO ECCM.CCECTRY VALUES('RO    ');
INSERT INTO ECCM.CCECTRY VALUES('SE    ');
INSERT INTO ECCM.CCECTRY VALUES('SG    ');
INSERT INTO ECCM.CCECTRY VALUES('US    ');
INSERT INTO ECCM.CCECTRY VALUES('ZA    ');
INSERT INTO ECCM.CCECTRY VALUES('KZ    ');


COMMIT WORK;


---------------------------------------------------
-- SUPPORTS ANOTHER SUMMARY TABLE IN THE TABLE SPEC
-- CONVERTED DWB
-- COMPILED DWB
-- CHECKED FOR FINAL SCRIPT
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
-- DDL Statements for table ECCM.ATTRUNITS
------------------------------------------------
DROP TABLE ECCM.ATTRUNITS;
CREATE TABLE ECCM.ATTRUNITS
 (
    attributetoken VARCHAR(36) NOT NULL,
    attributeunittoken VARCHAR(36) NOT NULL
 );

 CREATE UNIQUE INDEX ECCM.ATTRUNITS_PK ON ECCM.ATTRUNITS(ATTRIBUTETOKEN) INCLUDE (ATTRIBUTEUNITTOKEN);
 
 --
 --  DATA LOAD
 --

INSERT INTO ECCM.ATTRUNITS VALUES('PSGACOUSTICSAVE','PSGACOUSTICSAVEUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGAVGLAMPLIFE','PSGAVGLAMPLIFEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB1DEPTH_METRIC','PSGB1DEPTHUNIT_METRIC');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB1DEPTH_US','PSGB1DEPTHUNITS_US');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB1HEIGHT_METRIC','PSGB1HEIGHTUNITMETRIC');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB1HEIGHT_US','PSGB1HEIGHTUNITS_US');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB1WEIGHT_METRIC','PSGB1WEIGHTUNITMETRIC');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB1WEIGHT_US','PSGB1WEIGHTUNITS_US');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB1WIDTH_METRIC','PSGB1WIDTHUNIT_METRIC');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB1WIDTH_US','PSGB1WIDTHUNITS_US');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB2DEPTH_METRIC','PSGB2DEPTHUNIT_METRIC');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB2DEPTH_US','PSGB2DEPTHUNITS_US');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB2HEIGHT_METRIC','PSGB2HEIGHTUNITMETRIC');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB2HEIGHT_US','PSGB2HEIGHTUNITS_US');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB2WEIGHT_METRIC','PSGB2WEIGHTUNITMETRIC');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB2WEIGHT_US','PSGB2WEIGHTUNITS_US');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB2WIDTH_METRIC','PSGB2WIDTHUNIT_METRIC');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGB2WIDTH_US','PSGB2WIDTHUNITS_US');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGBACKUPTIME','PSGBACKUPTIMEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGBATPOWER','PSGBATPOWERUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGBATTERYVOLTAGE','PSGBATTERYVOLTAGEUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGBATTLIFERANGE','PSGBATTLIFERANGEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGBTTIMECOMP','PSGBTTIMECOMPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGBTTIMENATIVE','PSGBTTIMENATIVEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCABLELENGTH','PSGCABLELENGTHUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCACHESIZE_DC','PSGCACHESIZEUNITS_DC');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCACHESIZE_HD','PSGCACHESIZEUNITS_HD');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCDAVGACCTIME','PSGCDAVGACCTIMEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCD_CAPACITY','PSGCD_CAPACITYUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCHRGETIMEOFF','PSGCHRGETIMEOFFUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCHRGETIMEON ','PSGCHRGETIMEONUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCLEARDEPTHIMP','PSGCLEARDEPTHIMPUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCLEARDEPTHMET','PSGCLEARDEPTHMETUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCLEARHEIGHTIMP','PSGCLEARHEIGHTIMPUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCLEARHEIGHTMET','PSGCLEARHEIGHTMETUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCLEARWIDTHIMP','PSGCLEARWIDTHIMPUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGCLEARWIDTHMET','PSGCLEARWIDTHMETUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGDATATRNRATEAVG','PSGDATATRNRATEAVGUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGDEPTH_IMP','PSGDEPTH_IMPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGDEPTH_MET','PSGDEPTH_METUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGDIAGPITCH','PSGDGPTCHUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGDISTANCE','PSGDISTANCEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGEICOMPTHEOPERF','PSGEICOMPTHEOPERFUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGEIENERGYCONSUMP','PSGEIENERGYCONSUMPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGFDD_CAPACITY','PSGFDD_CAPACITYUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGFDD_SIZE','PSGFDD_SIZEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGFLASHMEMMAX','PSGFLASHMEMMAXUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGFLASHMEMSTD','PSGFLASHMEMSTDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHDAVGLAT_DF','PSGHDAVGLATUNITS_DF');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHDAVGLAT_HD','PSGHDAVGLATUNITS_HD');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHDAVGSEEKTIME','PSGHDAVGSEEKTIMEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHDDCAPACITY','PSGHDDCAPACITYUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHDDSIZE','PSGHDDSIZEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHEATEMISS','PSGHEATEMISSUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHEIGHT_IMP','PSGHEIGHT_IMPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHEIGHT_MET','PSGHEIGHT_METUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHORZPITCH','PSGHRZPTCHUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHZREFR_RATE_HI','PSGHZREFR_RATE_HIUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGHZREFR_RATE_LO','PSGHZREFR_RATE_LOUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGINCBLENGTH','PSGINCBLNGTHUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGINTL2CACHESIZE','PSGINTL2CACHESIZEUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGIRPORTSPEED','PSGIRPORTSPEEDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGJAPANENERGYEFFIC','PSGJAPANENERGYEFFICUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGKBCBLLENGTH','PSGKBCBLLENUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGL1INTPROCCACHE','PSGL1INTPROCCACHEUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGL2EXTCACHEMAX','PSGL2EXTCACHEMAXUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGL2EXTCACHESTD','PSGL2EXTCACHESTDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGL3CACHE','PSGL3CACHEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGL4CACHE','PSGL4CACHEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMAXINTHDCAPACITY','PSGMAXINTHDCAPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMAXPCITRANSRATE','PSGMAXPCITRANSRATEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMAXSCSITRANSRATE','PSGMAXSCSITRANSRATEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMEDIACAP','PSGMEDIACAPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMEMCAPACITY','PSGMEMCAPACITYUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMEMCASLAT','PSGMEMCASLATUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMEMORYACCESS','PSGMEMORYACCESSUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMEMRAMMAX','PSGMEMRAMMAXUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMEMRAMSTD','PSGMEMRAMSTDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMOB_PWRADC_LEN','PSGMOB_PWRADC_LENUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMOB_PWRADOUT','PSGMOB_PWRADOUTUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGMOBILEPOWERINVOLTS','PSGMOB_PWRINUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGOPERHUMID_MAX','PSGOPERHUMID_MAXUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGOPERHUMID_MIN','PSGOPERHUMID_MINUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGOPERTEMP_MAX','PSGOPERTEMP_MAXUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGOPERTEMP_MIN','PSGOPERTEMP_MINUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGOPSALTITUDE','PSGOPSALTITUDEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGPOINTDEVRES','PSGPOINTDEVRESUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGPOWERCONS','PSGPOWERCONSUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGPOWERSUPP','PSGPOWERSUPPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGPPTRAVEL_IMP','PSGPPTRAVEL_IMPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGPPTRAVEL_MET','PSGPPTRAVEL_METUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGPRCBUSSPEED','PSGPRCBUSSPEEDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGPROCCLKSPD','PSGPROCCLKSPDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGPWRCONSAVE','PSGPWRCONSAVEUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGPWRCONSTAND','PSGPWRCONSTANDUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGRAMSPEED','PSGRAMSPEEDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGROMSTANDARD','PSGROMSTANDARDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSAMPLERATE','PSGSAMPLERATEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSCRNHGHTMAXMET','PSGSCRNHGHTMAXMETUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSCRNWDTHMAXMET','PSGSCRNWDTHMAXMETUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSEEKTIME','PSGSEEKTIMEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSHIPHUMID_MAX','PSGSHIPHUMID_MAXUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSHIPHUMID_MIN','PSGSHIPHUMID_MINUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSHIPTEMP_MAX','PSGSHIPTEMP_MAXUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSHIPTEMP_MIN','PSGSHIPTEMP_MINUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSOUNDEMISS','PSGSOUNDEMISSUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSPEXVOLT','PSGSPEXVOLTUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSPFREQRESPSAT','PSGSPFREQRESPSATUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSPKRPOWRAT','PSGSPKRPOWRATUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSPSUBDRIVESZ','PSGSPSUBDRIVESZUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSPSUBPOWRATE','PSGSPSUBPOWRATEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSTMAXTRANRATE','PSGSTMAXTRANRATEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSTORCAPACITY','PSGSTORCAPACITYUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSTORCAPCOMP','PSGSTORCAPCOMPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSUSTRANRATE','PSGSUSTRANRATEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSUSTRS_RATEHI','PSGSUSTRS_RATEHIUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGSUSTRS_RATELO','PSGSUSTRS_RATELOUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGTOT_L2_CACHE_STD','PSGTOTL2CACHESTDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGTRANRATEAVG_DF ','PSGTRANRATEAVGUNIT_DF');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGTRANRATEMAX_HD','PSGTRANRATEMAXUNIT_HD');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGTRANRATEMIN_HD','PSGTRANRATEMINUNIT_HD');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGTRANS_RATE_AS','PSGTRANS_RATEUNITS_AS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGTRAVELLIFE','PSGTRAVELLIFEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGUPSBACKUPTIME','PSGUPSBACKUPTIMEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGUPSBATTRUNTIME','PSGUPSBATTRUNTIMEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGUPSBRICKVOLT','PSGUPSBRICKVOLTUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGUPSRECHARGETIME','PSGUPSRECHARGETIMEUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGVIDRAMMAX','PSGVIDRAMMAXUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGVIDRAMSTD','PSGVIDRAMSTDUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGVTREFR_RATE_HI','PSGVTREFR_RATE_HIUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGVTREFR_RATE_LO','PSGVTREFR_RATE_LOUNIT');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGWARMUP','PSGWARMUPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGWEIGHT_IMP','PSGWEIGHT_IMPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGWEIGHT_MET','PSGWEIGHT_METUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGWIDTH_IMP','PSGWIDTH_IMPUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGWIDTH_MET','PSGWIDTH_METUNITS');
INSERT INTO ECCM.ATTRUNITS VALUES('PSGWSMAXSPEED','PSGWSMAXSPEEDUNITS');

COMMIT WORK;

CREATE UNIQUE INDEX ECCM.ATTRUNITS_PK ECCM.ATTRUNITS(
------------------------------------------------
-- DDL Statements for table ECCM.PSGNLS
-- Reference table data
-- Converted DWB
-- CHECKED FOR FINAL SCRIPT
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
DROP TABLE ECCM.PSGNLS;
CREATE TABLE ECCM.PSGNLS
(NLSID INTEGER NOT NULL
,LANGDESC VARCHAR(32)
,ISOLANGCODE2 CHAR(2)
,ISOLANGCODE3 CHAR(3)
,IBMLANGCODE VARCHAR(6)
)
;
ALTER TABLE ECCM.PSGNLS PCTFREE 10;

-- DDL Statements for indexes on Table ECCM.PSGNLS

CREATE INDEX ECCM.TCPSGNLS ON ECCM.PSGNLS (NLSID ASC,ISOLANGCODE2 DESC);
CREATE UNIQUE INDEX ECCM.PSGNLS_PK ON ECCM.PSGNLS(NLSID);

--
-- LOAD DATA
--

INSERT INTO ECCM.PSGNLS VALUES(1,'US English','en','eng','ENG');
INSERT INTO ECCM.PSGNLS VALUES(2,'German','de','deu','DEU');
INSERT INTO ECCM.PSGNLS VALUES(3,'Italian','it','ita','ITA');
INSERT INTO ECCM.PSGNLS VALUES(4,'Japanese','ja','jpn','JPN');
INSERT INTO ECCM.PSGNLS VALUES(5,'French','fr','fra','FRA');
INSERT INTO ECCM.PSGNLS VALUES(6,'Spanish','es','spa','SPA');
INSERT INTO ECCM.PSGNLS VALUES(7,'UK English','en','eng','UKE');
INSERT INTO ECCM.PSGNLS VALUES(8,'Korean','ko','kor','KOR');
INSERT INTO ECCM.PSGNLS VALUES(9,'Chinese','zh','chi','CHI');
INSERT INTO ECCM.PSGNLS VALUES(10,'French Canadian','fr','fre','FRE');

COMMIT WORK;


------------------------------------------------
-- DDL Statements for table ECCM.PSGCTNLS
-- Reference table manually set up
--
-- CONVERTED DWB
-- CHECKED FOR FINAL SCRIPT
-- MADE DROP IMMUNE FROM ODSINIT
------------------------------------------------
DROP TABLE ECCM.PSGCTNLS;
CREATE TABLE ECCM.PSGCTNLS
(NLSID INTEGER NOT NULL
,COUNTRYCODE VARCHAR(6)NOT NULL
)
;

ALTER TABLE ECCM.PSGCTNLS PCTFREE 10;
CREATE UNIQUE INDEX ECCM.PSGCTNLS_PK ON ECCM.PSGCTNLS (NLSID, COUNTRYCODE);

--
-- LOAD DATA
-- 

INSERT INTO ECCM.PSGCTNLS VALUES(1,'US');
INSERT INTO ECCM.PSGCTNLS VALUES(2,'AT');
INSERT INTO ECCM.PSGCTNLS VALUES(2,'DE');
INSERT INTO ECCM.PSGCTNLS VALUES(3,'IT');
INSERT INTO ECCM.PSGCTNLS VALUES(4,'JP');
INSERT INTO ECCM.PSGCTNLS VALUES(5,'FR');
INSERT INTO ECCM.PSGCTNLS VALUES(6,'ES');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'AU');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'BE');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'CA');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'CH');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'CZ');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'DK');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'FI');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'GB');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'GR');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'HK');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'HR');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'HU');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'IE');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'IN');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'NL');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'NO');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'NZ');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'PL');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'PT');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'RO');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'SE');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'SG');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'ZA');
INSERT INTO ECCM.PSGCTNLS VALUES(8,'KR');
INSERT INTO ECCM.PSGCTNLS VALUES(10,'CA');
INSERT INTO ECCM.PSGCTNLS VALUES(7,'KZ');


COMMIT WORK;
