--
-- $Log: int.refload.sql,v $
-- Revision 1.4  2004/05/24 23:34:43  dave
-- more int cleanup for ECCM 2.0
--
-- Revision 1.3  2004/05/24 22:34:18  dave
-- int cleanup in prep for ECCM 2.0
--
-- Revision 1.2  2004/03/02 22:06:52  yang
-- updating and making final scripts
--

-------------------------------------------------------------
-- DROP THE TABLES RATHER THAN DELETE FROM THEM
-------------------------------------------------------------
drop table  int.avprdinvalidat;
drop table  int.avprdcat;
drop table  int.avprdat;
drop table  int.avwwprd;
drop table  int.avprdavail;
drop table  int.dacavail;
drop table  int.eccmatgp;
drop table  int.avcatroot;
drop table  int.avcatcatrel;
drop table  int.avcatcatseq;
drop table  int.avprice_state;
drop table  int.avprdprdseq;
drop table  int.currency_xchg;
drop table  int.avprdevp;
drop table  int.avprdcatseq;
drop table  int.newflagdates;
drop table  int.teamcatalog_deltaforce;
drop table  int.avcatim;
drop table  int.avwwcat;
drop table  int.eccmattr;
drop table  int.attrlabel;
drop table  int.familygroupattrseq;
drop table  int.avfamat;
drop table  int.attrgrouplabel;
drop table  int.avcatprodrelseqoptions;
drop table  int.avcatprodrelseqmanual;
drop table  int.avcatprodrelpubother;
drop table  int.avfamatroot;
drop table  int.avprdevproot;
drop table  int.avprodctry;
drop table  int.eccmtracker;
drop table  int.valid_price_range;
drop table  int.file_comment;
drop table  int.task_comment;
drop table  int.task;
drop table  int.workflow;
drop table  int.iwov_idmaps;
drop table  int.iwdeltracker;


--
-- Table Defs
--
------------------------------------------------
-- DDL Statements for table INT.AVWWPRD
------------------------------------------------
CREATE TABLE INT.AVWWPRD  (
      PRDSKU VARCHAR(254) NOT NULL , 
      PRDENTITYTYPE VARCHAR(36) , 
      PRDENTITYID INTEGER , 
      PRDNLSID INTEGER , 
      PARTNUMBER VARCHAR(36) , 
      COUNTRYCODE VARCHAR(6) , 
      LANGUAGE VARCHAR(6) , 
      PRODUCTCLASS VARCHAR(16) , 
      AUDIENCE VARCHAR(254) , 
      AUXDESC1 VARCHAR(1192) , 
      AUXDESC2 VARCHAR(254) , 
      SHORTDESC VARCHAR(254) , 
      ANNOUNCEDATE VARCHAR(30) , 
      WITHDRAWDATE VARCHAR(30) , 
      FOTANNOUNCEDATE VARCHAR(30) , 
      FOTWITHDRAWDATE VARCHAR(30) , 
      NAVBARFILENAME VARCHAR(254) , 
      CONFIGURATORID VARCHAR(254) , 
      FOTSTATUS VARCHAR(75) , 
      WWPARTNUM VARCHAR(36) , 
      INSTALLABLE INTEGER , 
      BASESYSTEM INTEGER , 
      SERVICETYPE VARCHAR(6) , 
      SPECIALBID VARCHAR(6) , 
      SBBTYPE VARCHAR(36) , 
      UNSPSC VARCHAR(200) , 
      UNUOM VARCHAR(200) , 
      PUB_FLAG INTEGER , 
      REVIEWPUB_FLAG INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
      REFRESHTIME TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
      VALID_FLAG INTEGER NOT NULL WITH DEFAULT 1, 
      INSTALLABLE_OVERRIDE INTEGER)   

IN USERSPACE1 ; 

ALTER TABLE INT.AVWWPRD PCTFREE 10;
ALTER TABLE INT.AVWWPRD VOLATILE CARDINALITY;

--
-- Indexes
--
CREATE INDEX INT.I_AVWWPRD_LANG ON INT.AVWWPRD (LANGUAGE ASC);
CREATE INDEX INT.WIZ2781 ON INT.AVWWPRD (PRDENTITYTYPE ASC, PRODUCTCLASS ASC, PARTNUMBER ASC, REFRESHTIME ASC, COUNTRYCODE ASC, PRDENTITYID ASC);
CREATE INDEX INT.WIZ3327 ON INT.AVWWPRD (PRODUCTCLASS ASC, PRDENTITYTYPE ASC, COUNTRYCODE ASC, REFRESHTIME ASC, PARTNUMBER ASC, PRDENTITYID ASC);
CREATE INDEX INT.WIZ3429 ON INT.AVWWPRD (COUNTRYCODE DESC);
CREATE INDEX INT.XIE1AVWWPRD ON INT.AVWWPRD(PRDENTITYTYPE ASC, PRDENTITYID ASC,PRDNLSID ASC,PRDSKU ASC) PCTFREE 10 CLUSTER ;
CREATE INDEX INT.XIE2AVWWPRD ON INT.AVWWPRD(PARTNUMBER ASC, COUNTRYCODE ASC) PCTFREE 10 ;
CREATE INDEX INT.XIE3AVWWPRD ON INT.AVWWPRD(COUNTRYCODE ASC, PRDENTITYTYPE ASC, PARTNUMBER ASC);
CREATE INDEX INT.XIE4AVWWPRD ON INT.AVWWPRD(PRDENTITYID ASC, PRDENTITYTYPE ASC);
ALTER TABLE INT.AVWWPRD ADD PRIMARY KEY (PRDSKU);


------------------------------------------------
-- DDL Statements for table INT.AVPRDCATSEQ
------------------------------------------------
CREATE TABLE INT.AVPRDCATSEQ  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      PARTNUMBER VARCHAR(36) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      LANGUAGE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      PUB_FLAG INTEGER , 
      SEQUENCE INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.AVPRDCATSEQ PCTFREE 10;
ALTER TABLE INT.AVPRDCATSEQ ADD PRIMARY KEY (CATIDENTIFIER, PARTNUMBER, COUNTRYCODE, LANGUAGE, AUDIENCE);

------------------------------------------------
-- DDL Statements for table INT.AVPRDEVP
------------------------------------------------
CREATE TABLE INT.AVPRDEVP  (
      PARTNUMBER VARCHAR(36) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      LANGUAGE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      EVP_INDICATOR CHAR(1) NOT NULL , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.AVPRDEVP ADD CONSTRAINT SQL020920182254320 PRIMARY KEY (PARTNUMBER, COUNTRYCODE, LANGUAGE, AUDIENCE, CATIDENTIFIER, EVP_INDICATOR);

------------------------------------------------
-- DDL Statements for table INT.CURRENCY_XCHG
------------------------------------------------
CREATE TABLE INT.CURRENCY_XCHG  (
      CURRENCYCODE VARCHAR(5) NOT NULL , 
      XCHGRATEMUL DECIMAL(30,15) NOT NULL , 
      XCHGRATEDIV DECIMAL(30,15) NOT NULL , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.CURRENCY_XCHG PCTFREE 10;

------------------------------------------------
-- DDL Statements for table INT.AVPRDPRDSEQ
------------------------------------------------
CREATE TABLE INT.AVPRDPRDSEQ  (
      PARENTPARTNUMBER VARCHAR(36) NOT NULL , 
      CHILDPARTNUMBER VARCHAR(36) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      PUB_FLAG INTEGER , 
      SEQUENCE INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.AVPRDPRDSEQ PCTFREE 10;
ALTER TABLE INT.AVPRDPRDSEQ ADD CONSTRAINT SQL020920182254390 PRIMARY KEY (PARENTPARTNUMBER, CHILDPARTNUMBER, COUNTRYCODE, AUDIENCE);

------------------------------------------------
-- DDL Statements for table INT.AVPRICE_STATE
------------------------------------------------
CREATE TABLE INT.AVPRICE_STATE  (
      PARTNUMBER VARCHAR(18) NOT NULL , 
      CTOVARIANTPARTNUMBER VARCHAR(18) NOT NULL , 
      COUNTRYCODE VARCHAR(3) NOT NULL , 
      DISTRIBUTIONCHANNEL VARCHAR(2) NOT NULL , 
      PRICEVALIDTODATE DATE NOT NULL , 
      PRICETYPE VARCHAR(2) NOT NULL , 
      MATERIALSTATUS VARCHAR(2) , 
      MATERIALSTATUSDATE DATE , 
      PRICEAMOUNT DECIMAL(16,3) , 
      CURRENCYCODE VARCHAR(5) , 
      PRICEVALIDFROMDATE DATE NOT NULL , 
      CALLFORQUOTE VARCHAR(1) , 
      STATE VARCHAR(5) NOT NULL , 
      PRECEDENCE SMALLINT , 
      SOURCESYSTEM VARCHAR(10) , 
      MARKEDFORDELETION CHAR(1) , 
      LASTUPDATED TIMESTAMP NOT NULL , 
      DELTA_TS TIMESTAMP NOT NULL )   
IN USERSPACE1 ; 
 
ALTER TABLE INT.AVPRICE_STATE VOLATILE CARDINALITY;
ALTER TABLE INT.AVPRICE_STATE ADD PRIMARY KEY(PARTNUMBER, CTOVARIANTPARTNUMBER, COUNTRYCODE, DISTRIBUTIONCHANNEL, PRICEVALIDTODATE, PRICETYPE);

CREATE INDEX INT.WIZ655 ON INT.AVPRICE_STATE (DISTRIBUTIONCHANNEL ASC, PRICEVALIDTODATE ASC, PRICEVALIDFROMDATE ASC, CALLFORQUOTE ASC);
CREATE INDEX INT.X010AVPRICESTATE ON INT.AVPRICE_STATE (DELTA_TS ASC) PCTFREE 10 ;

------------------------------------------------
-- DDL Statements for table INT.AVCATCATSEQ
------------------------------------------------
CREATE TABLE INT.AVCATCATSEQ  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      PARENTIDENTIFIER VARCHAR(254) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      PUB_FLAG INTEGER , 
      SEQUENCE INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.AVCATCATSEQ ADD CONSTRAINT SQL020920182254160 PRIMARY KEY (CATIDENTIFIER, PARENTIDENTIFIER, COUNTRYCODE, AUDIENCE);

------------------------------------------------
-- DDL Statements for table INT.AVCATCATREL
------------------------------------------------
CREATE TABLE INT.AVCATCATREL  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      PARENTIDENTIFIER VARCHAR(254) NOT NULL , 
      RELATIONSHIPONLY CHAR(1) NOT NULL , 
      SOURCE VARCHAR(8) , 
      MASTNAV CHAR(1) , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.AVCATCATREL PCTFREE 10;
ALTER TABLE INT.AVCATCATREL ADD PRIMARY KEY (CATIDENTIFIER, PARENTIDENTIFIER);

------------------------------------------------
-- DDL Statements for table INT.AVCATROOT
------------------------------------------------
CREATE TABLE INT.AVCATROOT  (
      PARENTIDENTIFIER VARCHAR(254) NOT NULL , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.AVCATROOT PCTFREE 10;
ALTER TABLE INT.AVCATROOT ADD PRIMARY KEY (PARENTIDENTIFIER);

------------------------------------------------
-- DDL Statements for table INT.ECCMATGP
------------------------------------------------
CREATE TABLE INT.ECCMATGP  (
      GROUPTOKEN VARCHAR(36) NOT NULL , 
      AUDIENCE_FLAG VARCHAR(18) , 
      GROUPDESCRIPTION VARCHAR(512) , 
      GROUPNAME VARCHAR(96) , 
      GROUPSORT INTEGER NOT NULL , 
      LASTUPDATED TIMESTAMP , 
      NEWGROUP CHAR(1) NOT NULL WITH DEFAULT 'Y', 
      ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +10000 , INCREMENT BY +1 , CACHE 20 ) )   
IN USERSPACE1 ; 

ALTER TABLE INT.ECCMATGP PCTFREE 10;
ALTER TABLE INT.ECCMATGP ADD PRIMARY KEY (GROUPTOKEN);

------------------------------------------------
-- DDL Statements for table INT.DACAVAIL
------------------------------------------------
CREATE TABLE INT.DACAVAIL  (
      PARTNUMBER VARCHAR(36) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      AVAILABLE_QUANTITY INTEGER , 
      SOURCE_SYSTEM VARCHAR(10) , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ;

ALTER TABLE INT.DACAVAIL PCTFREE 10;
ALTER TABLE INT.DACAVAIL ADD CONSTRAINT SQL020920182254440 PRIMARY KEY (PARTNUMBER, COUNTRYCODE);

CREATE INDEX INT.WZ1DACAVAIL1 ON INT.DACAVAIL (PARTNUMBER ASC, COUNTRYCODE ASC, LASTUPDATED ASC, SOURCE_SYSTEM ASC, AVAILABLE_QUANTITY ASC);

------------------------------------------------
-- DDL Statements for table INT.AVPRDAVAIL
------------------------------------------------
CREATE TABLE INT.AVPRDAVAIL  (
      PRDSKU VARCHAR(254) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      PRDENTITYTYPE VARCHAR(36) , 
      PRDENTITYID INTEGER , 
      PRDNLSID INTEGER , 
      PARTNUMBER VARCHAR(36) , 
      COUNTRYCODE VARCHAR(6) , 
      LANGUAGE VARCHAR(6) , 
      FOCUS_FLAG INTEGER , 
      NEW_FLAG INTEGER , 
      HIDE_FLAG INTEGER , 
      BUYABLE_FLAG INTEGER , 
      ADDTOCART_FLAG INTEGER , 
      CUSTOMIZE_FLAG INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
      RATETYPE INTEGER )   
IN USERSPACE1 ; 

ALTER TABLE INT.AVPRDAVAIL PCTFREE 10;
ALTER TABLE INT.AVPRDAVAIL  ADD PRIMARY KEY (PRDSKU,AUDIENCE);

CREATE INDEX INT.WIZ3943 ON INT.AVPRDAVAIL (LANGUAGE ASC, PARTNUMBER ASC);
CREATE INDEX INT.WZ1AVPRDAVAIL1 ON INT.AVPRDAVAIL (PARTNUMBER ASC, AUDIENCE ASC);
CREATE INDEX INT.XIE1AVPRDAVAIL ON INT.AVPRDAVAIL (PARTNUMBER ASC, COUNTRYCODE ASC, LANGUAGE ASC) PCTFREE 10 CLUSTER ;


------------------------------------------------
-- DDL Statements for table INT.NEWFLAGDATES
------------------------------------------------
CREATE TABLE INT.NEWFLAGDATES  (
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      NUMBEROFDAYS INTEGER NOT NULL , 
      LASTUPDATED TIMESTAMP NOT NULL )   
IN USERSPACE1 ; 

ALTER TABLE INT.NEWFLAGDATES PCTFREE 10;
ALTER TABLE INT.NEWFLAGDATES ADD PRIMARY KEY (COUNTRYCODE);


------------------------------------------------
-- DDL Statements for table INT.TEAMCATALOG_DELTAFORCE
------------------------------------------------
CREATE TABLE INT.TEAMCATALOG_DELTAFORCE  (
      CATEGORY VARCHAR(10) NOT NULL , 
      CATALOG VARCHAR(20) NOT NULL , 
      REGION VARCHAR(10) NOT NULL , 
      COUNTRYCODE CHAR(2) NOT NULL , 
      DELTA_INDICATOR TIMESTAMP NOT NULL )   
IN USERSPACE1 ; 

ALTER TABLE INT.TEAMCATALOG_DELTAFORCE PCTFREE 10;
ALTER TABLE INT.TEAMCATALOG_DELTAFORCE ADD PRIMARY KEY (CATEGORY, CATALOG, REGION, COUNTRYCODE);

CREATE INDEX INT.WIZ2 ON INT.TEAMCATALOG_DELTAFORCE (CATALOG ASC, DELTA_INDICATOR ASC, COUNTRYCODE ASC);

------------------------------------------------
-- DDL Statements for table INT.ECCMATTR
------------------------------------------------
 
CREATE TABLE INT.ECCMATTR  (
      ATTRIBUTETOKEN VARCHAR(36) NOT NULL , 
      LANGUAGE CHAR(2) NOT NULL , 
      AUDIENCE_FLAG VARCHAR(18) , 
      GROUPTOKEN VARCHAR(36) , 
      ATTRIBUTEDESCRIPTION VARCHAR(512) , 
      ATTRIBUTENAME VARCHAR(60) NOT NULL , 
      ATTRSORT INTEGER NOT NULL , 
      ATTRIBUTETYPE CHAR(1) , 
      COMPARISONONLY CHAR(1) NOT NULL , 
      LASTUPDATED TIMESTAMP , 
      NEWATTRIBUTE CHAR(1) NOT NULL WITH DEFAULT 'Y', 
      ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +10000 , INCREMENT BY +1 , CACHE 20 ) )   
IN USERSPACE1 ; 

ALTER TABLE INT.ECCMATTR PCTFREE 10;
ALTER TABLE INT.ECCMATTR ADD PRIMARY KEY (ATTRIBUTETOKEN, LANGUAGE);

CREATE INDEX INT.WZECCMATTR ON INT.ECCMATTR (GROUPTOKEN ASC, COMPARISONONLY ASC, ATTRIBUTETOKEN ASC, ATTRIBUTENAME ASC, ID ASC);

------------------------------------------------
-- DDL Statements for table INT.ATTRLABEL
------------------------------------------------
CREATE TABLE INT.ATTRLABEL  (
      NLSID INTEGER NOT NULL , 
      GROUPTOKEN VARCHAR(32) , 
      ATTRIBUTETOKEN VARCHAR(32) NOT NULL , 
      ATTRIBUTELABEL VARCHAR(254) , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.ATTRLABEL PCTFREE 20;
ALTER TABLE INT.ATTRLABEL ADD PRIMARY KEY (NLSID,ATTRIBUTETOKEN);

CREATE INDEX INT.XIE1ATTRLABEL ON INT.ATTRLABEL (ATTRIBUTETOKEN ASC, GROUPTOKEN ASC) PCTFREE 10 CLUSTER ;
CREATE INDEX INT.XIE2ATTRLABEL ON INT.ATTRLABEL (ATTRIBUTELABEL ASC);

------------------------------------------------
-- DDL Statements for table INT.FAMILYGROUPATTRSEQ
------------------------------------------------
CREATE TABLE INT.FAMILYGROUPATTRSEQ  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      GROUPTOKEN VARCHAR(36) NOT NULL , 
      ATTRIBUTETOKEN VARCHAR(36) NOT NULL , 
      GROUPSEQUENCE INTEGER NOT NULL , 
      GROUPVISIBLE INTEGER NOT NULL , 
      ATTRSEQUENCE INTEGER NOT NULL , 
      ATTRVISIBLE INTEGER NOT NULL , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.FAMILYGROUPATTRSEQ ADD PRIMARY KEY (CATIDENTIFIER, COUNTRYCODE, GROUPTOKEN, ATTRIBUTETOKEN);

------------------------------------------------
-- DDL Statements for table INT.AVCATIM
------------------------------------------------
CREATE TABLE INT.AVCATIM  (
      CATSKU VARCHAR(254) NOT NULL , 
      STATUS VARCHAR(75) NOT NULL , 
      COUNTRYCODE VARCHAR(6) , 
      LANGUAGE VARCHAR(6) , 
      IMAGEID INTEGER , 
      IMAGENAME VARCHAR(150) , 
      FROMDATE VARCHAR(30) , 
      TODATE VARCHAR(30) , 
      PREVIEWFROM VARCHAR(30) , 
      PREVIEWTO VARCHAR(30) , 
      ECCM_IMAGEID INTEGER , 
      ECCM_IMAGENAME VARCHAR(150) , 
      ECCM_FROMDATE VARCHAR(30) , 
      ECCM_TODATE VARCHAR(30) , 
      ECCM_PREVIEWFROM VARCHAR(30) , 
      ECCM_PREVIEWTO VARCHAR(30) , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 
ALTER TABLE INT.AVCATIM PCTFREE 10;
ALTER TABLE INT.AVCATIM ADD PRIMARY KEY (CATSKU, STATUS);

------------------------------------------------
-- DDL Statements for table INT.AVFAMAT
------------------------------------------------
CREATE TABLE INT.AVFAMAT  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      LANGUAGE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      ATTRIBTOKEN VARCHAR(254) NOT NULL , 
      COLSEQUENCE INTEGER NOT NULL , 
      ROWSEQUENCE INTEGER NOT NULL , 
      DESCRIPTION VARCHAR(512) , 
      VIEWBY INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 
 
ALTER TABLE INT.AVFAMAT PCTFREE 10;
ALTER TABLE INT.AVFAMAT ADD PRIMARY KEY (CATIDENTIFIER, COUNTRYCODE, LANGUAGE, AUDIENCE, ATTRIBTOKEN, COLSEQUENCE, ROWSEQUENCE);

CREATE INDEX INT.XIE1AVFAMAT ON INT.AVFAMAT (COUNTRYCODE ASC, LANGUAGE ASC, AUDIENCE ASC) PCTFREE 19 CLUSTER ;

------------------------------------------------
-- DDL Statements for table INT.AVPRDCAT
------------------------------------------------
CREATE TABLE INT.AVPRDCAT  (
      PRDSKU VARCHAR(254) NOT NULL , 
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      PRDENTITYTYPE VARCHAR(36) , 
      PRDENTITYID INTEGER , 
      PRDNLSID INTEGER , 
      PARTNUMBER VARCHAR(36) , 
      COUNTRYCODE VARCHAR(6) , 
      LANGUAGE VARCHAR(6) , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 
 
ALTER TABLE INT.AVPRDCAT PCTFREE 10;
ALTER TABLE INT.AVPRDCAT ADD PRIMARY KEY (PRDSKU, CATIDENTIFIER, AUDIENCE);

CREATE INDEX INT.XIE1AVPRDCAT ON INT.AVPRDCAT (CATIDENTIFIER ASC, PARTNUMBER ASC, COUNTRYCODE ASC, LANGUAGE ASC, PRDNLSID ASC) PCTFREE 10 CLUSTER ;

------------------------------------------------
-- DDL Statements for table INT.ATTRGROUPLABEL
------------------------------------------------
CREATE TABLE INT.ATTRGROUPLABEL  (
      NLSID INTEGER NOT NULL , 
      GROUPTOKEN VARCHAR(32) NOT NULL , 
      ATTRIBUTELABEL VARCHAR(254) , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 
 
ALTER TABLE INT.ATTRGROUPLABEL PCTFREE 10;
ALTER TABLE INT.ATTRGROUPLABEL ADD PRIMARY KEY (GROUPTOKEN, NLSID);

------------------------------------------------
-- DDL Statements for table INT.AVCATPRODRELSEQOPTIONS
------------------------------------------------
CREATE TABLE INT.AVCATPRODRELSEQOPTIONS  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      LANGUAGE VARCHAR(6) NOT NULL , 
      ORDERBY_FLAG VARCHAR(10) , 
      ORDER_AD INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL )   
IN USERSPACE1 ; 
 
ALTER TABLE INT.AVCATPRODRELSEQOPTIONS PCTFREE 10;
ALTER TABLE INT.AVCATPRODRELSEQOPTIONS ADD PRIMARY KEY (CATIDENTIFIER, COUNTRYCODE, AUDIENCE, LANGUAGE);

------------------------------------------------
-- DDL Statements for table INT.AVCATPRODRELSEQMANUAL
------------------------------------------------
CREATE TABLE INT.AVCATPRODRELSEQMANUAL  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      PARTNUMBER VARCHAR(36) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      LANGUAGE VARCHAR(6) NOT NULL , 
      PUB_FLAG INTEGER , 
      SEQUENCE INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL )   
IN USERSPACE1 ; 

ALTER TABLE INT.AVCATPRODRELSEQMANUAL PCTFREE 10;
ALTER TABLE INT.AVCATPRODRELSEQMANUAL ADD PRIMARY KEY (CATIDENTIFIER, PARTNUMBER, COUNTRYCODE, AUDIENCE, LANGUAGE);

------------------------------------------------
-- DDL Statements for table INT.AVCATPRODRELPUBOTHER
------------------------------------------------
CREATE TABLE INT.AVCATPRODRELPUBOTHER  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      LANGUAGE VARCHAR(6) NOT NULL , 
      PARTNUMBER VARCHAR(36) NOT NULL , 
      PUB_FLAG INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL )   
IN USERSPACE1 ; 
 
ALTER TABLE INT.AVCATPRODRELPUBOTHER PCTFREE 10;
ALTER TABLE INT.AVCATPRODRELPUBOTHER ADD PRIMARY KEY (CATIDENTIFIER, COUNTRYCODE, AUDIENCE, LANGUAGE, PARTNUMBER);

------------------------------------------------
-- DDL Statements for table INT.AVFAMATROOT
------------------------------------------------
CREATE TABLE INT.AVFAMATROOT  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      LANGUAGE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 

ALTER TABLE INT.AVFAMATROOT PCTFREE 10;
ALTER TABLE INT.AVFAMATROOT ADD CONSTRAINT PKAVFAMATROOT PRIMARY KEY (CATIDENTIFIER, COUNTRYCODE, LANGUAGE, AUDIENCE);

------------------------------------------------
-- DDL Statements for table INT.AVPRDEVPROOT
------------------------------------------------
CREATE TABLE INT.AVPRDEVPROOT  (
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      COUNTRYCODE VARCHAR(6) NOT NULL , 
      LANGUAGE VARCHAR(6) NOT NULL , 
      AUDIENCE VARCHAR(254) NOT NULL , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN USERSPACE1 ; 
 
ALTER TABLE INT.AVPRDEVPROOT PCTFREE 10;
ALTER TABLE INT.AVPRDEVPROOT ADD PRIMARY KEY (CATIDENTIFIER, COUNTRYCODE, LANGUAGE, AUDIENCE);

------------------------------------------------
-- DDL Statements for table INT.AVPRODCTRY
------------------------------------------------
CREATE TABLE INT.AVPRODCTRY  (
      PARTNUMBER VARCHAR(36) NOT NULL , 
      COUNTRYCODE CHAR(2) NOT NULL , 
      LANGUAGE CHAR(2) NOT NULL , 
      AUDIENCE VARCHAR(18) NOT NULL , 
      ADDTOCARTCUSTOMIZE INTEGER , 
      BUYABLE CHAR(10) , 
      PAGENAME VARCHAR(254) , 
      QUANTITY CHAR(10) , 
      SALESTATUS CHAR(2) , 
      LASTUPDATED TIMESTAMP )   
IN USERSPACE1 ; 

ALTER TABLE INT.AVPRODCTRY PCTFREE 10;
ALTER TABLE INT.AVPRODCTRY ADD PRIMARY KEY (PARTNUMBER, COUNTRYCODE, LANGUAGE, AUDIENCE);

------------------------------------------------
-- DDL Statements for table INT.ECCMTRACKER
------------------------------------------------
 
CREATE TABLE INT.ECCMTRACKER  (
      SKU VARCHAR(254) NOT NULL , 
      PARTNUMBER VARCHAR(36) , 
      COUNTRYCODE VARCHAR(6) , 
      LANGUAGE VARCHAR(6) , 
      SERIES VARCHAR(254) , 
      FAMILY VARCHAR(254) , 
      CATIDENTIFIER VARCHAR(254) , 
      PATH VARCHAR(512) , 
      VPATH VARCHAR(512) , 
      LASTUPDATED TIMESTAMP )   
IN USERSPACE1 ; 

ALTER TABLE INT.ECCMTRACKER PCTFREE 10;
ALTER TABLE INT.ECCMTRACKER ADD PRIMARY KEY (SKU);

CREATE INDEX INT.IC2CCMTRACKER ON INT.ECCMTRACKER (PARTNUMBER DESC, COUNTRYCODE ASC, LANGUAGE ASC);
CREATE INDEX INT.ICECCMTRACKER ON INT.ECCMTRACKER (CATIDENTIFIER DESC);

------------------------------------------------
-- DDL Statements for table INT.VALID_PRICE_RANGE
------------------------------------------------
CREATE TABLE INT.VALID_PRICE_RANGE  (
      FAMILYNAME VARCHAR(60) NOT NULL , 
      MIN_PRICE DECIMAL(16,3) NOT NULL , 
      MAX_PRICE DECIMAL(16,3) NOT NULL )   
IN USERSPACE1 ; 
 
ALTER TABLE INT.VALID_PRICE_RANGE PCTFREE 10;
ALTER TABLE INT.VALID_PRICE_RANGE ADD PRIMARY KEY (FAMILYNAME);

------------------------------------------------
-- DDL Statements for table INT.AVPRDINVALIDAT
------------------------------------------------
CREATE TABLE INT.AVPRDINVALIDAT  (
      PRDSKU VARCHAR(254) NOT NULL , 
      ATTRIBUTETOKEN VARCHAR(36) NOT NULL , 
      PRDENTITYTYPE VARCHAR(36) , 
      PRDENTITYID INTEGER , 
      PRDNLSID INTEGER , 
      PARTNUMBER VARCHAR(36) , 
      COUNTRYCODE VARCHAR(6) , 
      LANGUAGE VARCHAR(6) , 
      VALUE VARCHAR(8192) , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN TSPACE02 ; 
 
ALTER TABLE INT.AVPRDINVALIDAT PCTFREE 10;
ALTER TABLE INT.AVPRDINVALIDAT  ADD PRIMARY KEY (PRDSKU, ATTRIBUTETOKEN);


------------------------------------------------
-- DDL Statements for table INT.FILE_COMMENT
------------------------------------------------
CREATE TABLE INT.FILE_COMMENT  (
      FILE_COMMENT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +1 , INCREMENT BY +1 , CACHE 20 ) , 
      WORKFLOW_ID INTEGER , 
      TASK_ID INTEGER , 
      FILENAME VARCHAR(127) , 
      DATE TIMESTAMP , 
      USER VARCHAR(45) NOT NULL , 
      BODY VARCHAR(2000) )   
IN USERSPACE1 ; 

ALTER TABLE INT.FILE_COMMENT PCTFREE 10;
ALTER TABLE INT.FILE_COMMENT ADD PRIMARY KEY (FILE_COMMENT_ID);

------------------------------------------------
-- DDL Statements for table INT.TASK_COMMENT
------------------------------------------------
CREATE TABLE INT.TASK_COMMENT  (
      TASK_COMMENT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +1 , INCREMENT BY +1 , CACHE 20 ) , 
      TASK_ID INTEGER , 
      DATE DATE NOT NULL , 
      USER VARCHAR(45) NOT NULL , 
      BODY VARCHAR(2000) )   
IN USERSPACE1 ; 

ALTER TABLE INT.TASK_COMMENT PCTFREE 10;
ALTER TABLE INT.TASK_COMMENT ADD PRIMARY KEY (TASK_COMMENT_ID);

------------------------------------------------
-- DDL Statements for table INT.TASK
------------------------------------------------
CREATE TABLE INT.TASK  (
      TASK_ID INTEGER NOT NULL , 
      WORKFLOW_ID INTEGER NOT NULL , 
      NAME VARCHAR(256) NOT NULL , 
      OWNER VARCHAR(45) NOT NULL , 
      TYPE VARCHAR(20) NOT NULL , 
      ACTIVATION INTEGER , 
      UNACTIVATION INTEGER )   
IN USERSPACE1 ; 

ALTER TABLE INT.TASK PCTFREE 10;
ALTER TABLE INT.TASK ADD PRIMARY KEY (TASK_ID);

------------------------------------------------
-- DDL Statements for table INT.WORKFLOW
------------------------------------------------
CREATE TABLE INT.WORKFLOW  (
      WORKFLOW_ID INTEGER NOT NULL , 
      NAME VARCHAR(256) NOT NULL , 
      OWNER VARCHAR(45) NOT NULL , 
      CREATOR VARCHAR(45) NOT NULL )   
IN USERSPACE1 ; 

ALTER TABLE INT.WORKFLOW PCTFREE 10;
ALTER TABLE INT.WORKFLOW ADD PRIMARY KEY (WORKFLOW_ID);


------------------------------------------------
-- DDL Statements for table INT.IWOV_IDMAPS
------------------------------------------------
CREATE TABLE INT.IWOV_IDMAPS  (
      TYPE INTEGER NOT NULL , 
      SHORTID VARCHAR(30) NOT NULL , 
      LONGID VARCHAR(1024) NOT NULL )   
IN USERSPACE1 ; 
 
ALTER TABLE INT.IWOV_IDMAPS PCTFREE 10;
CREATE INDEX INT.IWOV_IDMAPS_INDEX ON INT.IWOV_IDMAPS (TYPE ASC);

------------------------------------------------
-- DDL Statements for table INT.IWDELTRACKER
------------------------------------------------
CREATE TABLE INT.IWDELTRACKER  (
      PATH VARCHAR(255) NOT NULL , 
      AREA VARCHAR(255) NOT NULL , 
      KEYCOLNAME VARCHAR(255) NOT NULL , 
      KEYCOLVALUE VARCHAR(255) NOT NULL )   
IN USERSPACE1 ; 

ALTER TABLE INT.IWDELTRACKER PCTFREE 10;

CREATE INDEX INT.IWDELT_IDX ON INT.IWDELTRACKER (PATH ASC, AREA ASC);

------------------------------------------------
-- DDL Statements for table INT.AVPRDAT
------------------------------------------------
CREATE TABLE INT.AVPRDAT  (
      PRDSKU VARCHAR(254) NOT NULL , 
      ATTRIBUTETOKEN VARCHAR(36) NOT NULL , 
      PRDENTITYTYPE VARCHAR(36) , 
      PRDENTITYID INTEGER , 
      PRDNLSID INTEGER , 
      PARTNUMBER VARCHAR(36) , 
      COUNTRYCODE VARCHAR(6) , 
      LANGUAGE VARCHAR(6) , 
      VALUE VARCHAR(8192) , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
IN TSPACE02 ; 

ALTER TABLE INT.AVPRDAT PCTFREE 10;
ALTER TABLE INT.AVPRDAT ADD PRIMARY KEY (PRDSKU, ATTRIBUTETOKEN);

CREATE INDEX INT.WZKAVPRDAT ON INT.AVPRDAT (ATTRIBUTETOKEN ASC, PRDENTITYID DESC, PRDNLSID ASC);
CREATE INDEX INT.XIE1AVPRDAT ON INT.AVPRDAT (COUNTRYCODE ASC, LANGUAGE ASC) PCTFREE 10 CLUSTER ;

------------------------------------------------
-- DDL Statements for table INT.AVWWCAT
------------------------------------------------
CREATE TABLE INT.AVWWCAT  (
      CATSKU VARCHAR(254) NOT NULL , 
      CATIDENTIFIER VARCHAR(254) NOT NULL , 
      COUNTRYCODE VARCHAR(6) , 
      LANGUAGE VARCHAR(6) , 
      AUDIENCE VARCHAR(254) , 
      NAME VARCHAR(254) , 
      NAMEDESC VARCHAR(254) , 
      NAMELONGDESC VARCHAR(8192) , 
      DISPLAY VARCHAR(254) , 
      SERIESHEADING VARCHAR(254) , 
      IMAGEDISCLAIMER VARCHAR(300) , 
      PRICEDISCLAIMER VARCHAR(300) , 
      FEATURE VARCHAR(8192) , 
      FOOTNOTE VARCHAR(8192) , 
      PAGENAME VARCHAR(254) , 
      LEVEL INTEGER , 
      PUB_FLAG INTEGER , 
      LASTUPDATED TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
      SEARCHTITLE VARCHAR(500) , 
      SEARCHKEYWORD VARCHAR(1000) , 
      SEARCHABSTRACT VARCHAR(500) , 
      SEARCHDESC VARCHAR(500) , 
      SEARCHCATEGORY VARCHAR(1000) , 
      SEARCHDOCTYPE VARCHAR(200) )   
IN INTTBSPBIG ; 
 
ALTER TABLE INT.AVWWCAT PCTFREE 10;
ALTER TABLE INT.AVWWCAT ADD PRIMARY KEY (CATSKU);

------------------------------------------------
-- DDL Statements for table INT.BRIO_STATUS
------------------------------------------------
CREATE TABLE INT.BRIO_STATUS  (
      ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +1 , INCREMENT BY +1 , CACHE 20 ) , 
      TABLE_NAME CHAR(36) NOT NULL , 
      TYPE CHAR(10) NOT NULL , 
      START_TIME TIMESTAMP NOT NULL , 
      END_TIME TIMESTAMP , 
      TIMETAKEN INTEGER GENERATED ALWAYS AS (END_TIME - START_TIME) , 
      STATUS CHAR(18) NOT NULL )   
IN USERSPACE1 ; 

ALTER TABLE INT.BRIO_STATUS ADD PRIMARY KEY (ID);


-------------------------------------------
-- REFERENTIAL INTEGRITY
-------------------------------------------

ALTER TABLE INT.AVPRDEVP ADD CONSTRAINT "SQL031120094103150" FOREIGN KEY (CATIDENTIFIER, COUNTRYCODE, LANGUAGE, AUDIENCE)
REFERENCES INT.AVPRDEVPROOT (CATIDENTIFIER,COUNTRYCODE,LANGUAGE,AUDIENCE)
ON DELETE CASCADE ON UPDATE NO ACTION;


ALTER TABLE INT.AVFAMAT ADD CONSTRAINT "SQL031120094100260" FOREIGN KEY (CATIDENTIFIER, COUNTRYCODE, LANGUAGE,AUDIENCE)
REFERENCES INT.AVFAMATROOT (CATIDENTIFIER,COUNTRYCODE,LANGUAGE,AUDIENCE)
ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE INT.AVPRDCAT ADD CONSTRAINT "SQL031006015950300" FOREIGN KEY (PRDSKU)
REFERENCES INT.AVWWPRD (PRDSKU) ON DELETE CASCADE ON UPDATE NO ACTION;


ALTER TABLE INT.AVPRDINVALIDAT  ADD CONSTRAINT "SQL031120094101060" FOREIGN KEY (PRDSKU)
REFERENCES INT.AVWWPRD (PRDSKU) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE INT.AVPRDAT  ADD   FOREIGN KEY (PRDSKU)
REFERENCES INT.AVWWPRD (PRDSKU) ON DELETE CASCADE ON UPDATE NO ACTION
DATA CAPTURE NONE  NOT VOLATILE;

ALTER TABLE INT.AVCATIM  ADD   FOREIGN KEY (CATSKU)
REFERENCES INT.AVWWCAT (CATSKU) ON DELETE CASCADE ON UPDATE NO ACTION
DATA CAPTURE NONE  NOT VOLATILE;
