//
// Copyright (c) 2001, International Business Machines Corp., Ltd.
// All Rights Reserved.
// Licensed for use in connection with IBM business only.
//
// $Log: MetaRow.java,v $
// Revision 1.6  2005/03/08 23:15:46  dave
// Jtest checkins from today and last ngith
//
// Revision 1.5  2003/03/14 17:54:18  gregg
// remove remote pdh update method from MetaRow class - instead update using db through remote interface
//
// Revision 1.4  2003/03/12 20:52:49  gregg
// add updatePdhRemote method to ALL MetaRows
//
// Revision 1.3  2002/08/23 22:15:21  gregg
// updatePdhMeta method - only throw MiddlewareException
//
// Revision 1.2  2002/03/07 00:56:08  gregg
// override EANMetaFoundation's toString() method
//
// Revision 1.1  2002/03/01 18:28:11  gregg
// initial load
//
//

package COM.ibm.eannounce.objects;

import COM.ibm.opicmpdh.middleware.Profile;
import COM.ibm.opicmpdh.middleware.Database;
import COM.ibm.opicmpdh.middleware.MiddlewareException;
import COM.ibm.opicmpdh.middleware.MiddlewareRequestException;

/**
* Abstract class which will form the basis for one 'Meta' row in the PDH.
*
*/
public abstract class MetaRow extends EANMetaFoundation {

    /**
    * @serial
    */
    static final long serialVersionUID = 1L;

    /**
     * FIELD
     */
    protected String m_strValFrom = null;
    /**
     * FIELD
     */
    protected String m_strValTo = null;
    /**
     * FIELD
     */
    protected String m_strEffFrom = null;
    /**
     * FIELD
     */
    protected String m_strEffTo = null;
    /**
     * FIELD
     */
    protected int m_iTranId = -1;

    /**
     * MetaRow
     *
     * @param _prof
     * @param _strKey
     * @param _strValFrom
     * @param _strValTo
     * @param _strEffFrom
     * @param _strEffTo
     * @param _iTranId
     * @throws COM.ibm.opicmpdh.middleware.MiddlewareRequestException
     *  @author David Bigelow
     */
    public MetaRow(Profile _prof, String _strKey, String _strValFrom, String _strValTo, String _strEffFrom, String _strEffTo, int _iTranId) throws MiddlewareRequestException {
        super(null, _prof, _strKey);
        setValFrom(_strValFrom);
        setValTo(_strValTo);
        setEffFrom(_strEffFrom);
        setEffTo(_strEffTo);
        setTranID(_iTranId);
        return;
    }

    /**
     * Mutator
     *
     * @param _s 
     */
    public void setValFrom(String _s) {
        m_strValFrom = _s;
        return;
    }

    /**
     * Accessor
     *
     * @return String
     */
    public String getValFrom() {
        return m_strValFrom;
    }

    /**
     * Mutator
     *
     * @param _s 
     */
    public void setValTo(String _s) {
        m_strValTo = _s;
        return;
    }

    /**
     * Accessor
     *
     * @return String
     */
    public String getValTo() {
        return m_strValTo;
    }

    /**
     * Mutator
     *
     * @param _s 
     */
    public void setEffFrom(String _s) {
        m_strEffFrom = _s;
        return;
    }

    /**
     * Accessor
     *
     * @return String
     */
    public String getEffFrom() {
        return m_strEffFrom;
    }

    /**
     * Mutator
     *
     * @param _s 
     */
    public void setEffTo(String _s) {
        m_strEffTo = _s;
        return;
    }

    /**
     * Accessor
     *
     * @return String
     */
    public String getEffTo() {
        return m_strEffTo;
    }

    /**
     * Accessor
     *
     * @return String
     */
    public String getEnterprise() {
        return getProfile().getEnterprise();
    }

    /**
     * Accessor
     *
     * @return int
     */
    public int getOPWGID() {
        return getProfile().getOPWGID();
    }

    /**
     * Mutator
     *
     * @param _i 
     */
    public void setTranID(int _i) {
        m_iTranId = _i;
        return;
    }

    /**
     * Accessor
     *
     * @return int
     */
    public int getTranID() {
        return m_iTranId;
    }

    /**
     * update this row into the PDH
     *
     * @param _db
     * @throws COM.ibm.opicmpdh.middleware.MiddlewareException 
     */
    public abstract void updatePdh(Database _db) throws MiddlewareException;

    /**
     * Get the version Id - generated by CVS
     *
     * @return String
     */
    public String getVersion() {
        return "$Id: MetaRow.java,v 1.6 2005/03/08 23:15:46 dave Exp $";
    }

    /**
     * override EANMetaFoundation's toString() method
     *
     * @return String
     */
    public String toString() {
        return dump(false);
    }

}
